name: period_tracking
description: A period tracking application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  table_calendar: ^3.0.9
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^9.9.1
  timezone: ^0.8.0
  intl: ^0.19.0
  fl_chart: ^0.65.0  # 更新到最新版本
  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true